{% set name = "django-celery-beat" %}
{% set version = "2.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8482034925e09b698c05ad61c36ed2a8dbc436724a3fe119215193a4ca6dc967

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - celery >=5.2.3,<6.0
    - importlib-metadata
    - django-timezone-field >=5.0
    - backports.zoneinfo
    - tzdata
    - python-crontab >=2.3.4
    - cron-descriptor >=1.2.32
    - django >=2.2,<5.2

test:
  imports:
    - django_celery_beat
    - django_celery_beat.migrations
  requires:
    - pip

about:
  home: https://github.com/celery/django-celery-beat
  summary: Database-backed Periodic Tasks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
