{% set name = "django-celery-beat" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58efe9460e4373a241c2b3d839518f29a28ae19bc80a8dba20da204c7ea50613

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - celery >=5.0,<6.0
    - django >=1.11.17
    - django-timezone-field >=4.1.0,<5.0
    - python >=3.6
    - python-crontab >=2.3.4

test:
  imports:
    - django_celery_beat
    - django_celery_beat.migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/celery/django-celery-beat
  summary: Database-backed Periodic Tasks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
