{% set name = "django-celery-beat" %}
{% set version = "2.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dfad0201c0ac50c91a34700ef8fa0a10ee098cc7f3375fe5debed79f2204f80a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - celery >=5.2.3,<6.0
    - importlib-metadata
    - django-timezone-field >=5.0
    - backports.zoneinfo
    - tzdata
    - python-crontab >=2.3.4
    - cron-descriptor >=1.2.32
    - django >=2.2,<6.0

test:
  imports:
    - django_celery_beat
    - django_celery_beat.migrations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/celery/django-celery-beat
  summary: Database-backed Periodic Tasks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
